### ISSUE TITLE
Bug: First alignment on header line

### ISSUE THREAD

**Issue by nathanhaigh** [csiro-crop-informatics/biokanga#4]
I've also noticed that the first alignment (not sure if this is in every case) appears on the last line of the BAM/header. e.g. Probably just a missing new line character at the end of the @PG header line.

```
@PG     ID:biokanga     VN:4.3.5HWI-ST226:209:D04H2ACXX:4:1107:8119:199917      99      chr1A   293     255     62M     =       484     269     CTCGAGCT
```

**Comment by kit4b** [comment]
I think the problem actually lies with Samtools not correctly processing according to the BAM specification when transforming from BAM to SAM.
The BAM specification V1 (dated 28th April 2016), and earlier versions, explicitly state that in the BAM format then the header section (‘text’) is optionally NULL (‘\0’ referenced as ASCII NUL)  terminated, with the length (‘l_text’) of the header to be inclusive of any NUL terminators. There is no, either implicit or explicit, requirement in the specification for the last line of the header section to be new line terminated. In the BAM format the list of alignments is separate to the header section, it is the responsibility of the BAM parser to check for the existence, or otherwise, of a header section terminating new line and determine if a new line should be prepended to the transformed (from the BAM binary structured alignment representation) to ASCII SAM alignment representation.

Problem is that a new line termination can easily be appended to the BAM header section by BioKanga; but downstream processing applications could be assuming no new line termination and always adding one themselves thus there will be two newlines between the header and first alignment. This may break these downstream applications in that they may then process as though there were no alignments when then processing the resultant SAM files. 

There are unlikely to be any issues if applications are processing the BAM file directly, after appending a new line to the header contents,  because of the structured separation between the header and alignments.  These applications are aware of the structured separation and may completely ignore the header content as the individual sequence names and their lengths are present in another list which is independent of either the header or alignments.

**Comment by nathanhaigh** [comment]
You're right, the spec says the header is not be null-terminated: https://github.com/samtools/hts-specs/blob/master/SAMv1.tex#L795

I also ran `samtools quickcheck -vvv ${BAM_FILE}` and it didn't show any issues.

I've filed a bug report here: https://github.com/samtools/samtools/issues/661

**Comment by kit4b** [comment]
Commented on the samtools bug report #661 in that the issue is not as to if the BAM header block is NUL ('\0') terminated but rather that the last line of the BAM header block is not required to have a NL ('\n') as the last char immediately before any terminating NUL.

**Comment by daviesrob** [comment]
I don't think this problem has been mentioned before, so I suspect that almost all BAM files include the newline on the last line of the header.

@ste69r wrote:
> Problem is that a new line termination can easily be appended to the BAM header section by BioKanga; but downstream processing applications could be assuming no new line termination and always adding one themselves thus there will be two newlines between the header and first alignment.

Any tool that assumes no newline at the end of the BAM header would have to be horribly broken, given that most (if not all) BAM files do have it.  I don't see any harm in adding one if it's not already present.

**Comment by kit4b** [comment]
If BAM is processed directly (majority of applications) then it doesn’t matter how the BAM header section is terminated as the header is generally ignored; it does matter if an application is naively copying the header without checking the header terminator and prepending same onto the first alignment which is what Samtools is doing when converting BAM to SAM.
Bioinformatics tools need to become more robust …

**Comment by kit4b** [comment]
Workaround being considered until such time as SAMtools patch for #661 has been released.
